[package]
name = "mm_archive"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
zip = { version = "*", optional = true }
lending-iterator = "*"
serde = "*"
time = "*"

[features]
default = ["zip"]
